version: '2'

services:
  init:
    image: koding/base
    working_dir: /opt/koding
    entrypoint: scripts/bootstrap-container
    command: configure
    env_file: .env-docker-compose
    volumes:
      - .:/opt/koding

  backend:
    image: koding/base
    working_dir: /opt/koding
    entrypoint: scripts/bootstrap-container
    command: run backend
    env_file: .env-docker-compose
    volumes:
      - .:/opt/koding
    ports:
      - 8090:8090
    links:
      - mongo
      - postgres
      - rabbitmq
      - redis

  client:
    image: koding/base
    working_dir: /opt/koding
    entrypoint: scripts/bootstrap-container is_ready
    command: make -C client development
    env_file: .env-docker-compose
    volumes:
      - .:/opt/koding

  mongo:
    image: koding/mongo

  postgres:
    image: koding/postgres

  rabbitmq:
    image: rabbitmq:3-management

  redis:
    image: redis
