mongourl   = ""
dryrun     = true
debug      = true
hostedzone = "koding.io"
interval   = "6h"

[slack]
url = "https://hooks.slack.com/services/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"

[postgres]
host = ""
port = 5432
username = ""
password = ""
dbname = ""

[aws]
accesskey = ""
secretkey = ""


