EventExchangeName="BrokerMessageBus"
Mongo="dev:k9lc4G1k32nyD72@172.16.3.9:27017/koding"
Environment="production"
Redis="172.16.10.16:6379"
# slave one is not used, just here for future ref
RedisSlave="172.16.10.17:6379"

[postgres]
Host=     "localhost"
Port=     5432
Username= "socialapplication"
Password= "socialapplication"
DBName=   "social"

[mq]
Host=     "172.16.3.4"
Port=     5672
Username= "guest"
Password= "Xah8ibeekelah"
Vhost=    "new"

[limits]
MessageBodyMinLen=5
