EventExchangeName = "BrokerMessageBus"
Mongo             = "10.0.0.137:27017/koding"
Environment       = "sandbox"
Region            = "sandbox"
Uri               = "http://sandbox.koding.io"
DisableCaching    = false


[postgres]
Host     = "10.0.0.137"
Port     = 5432
Username = "socialapplication"
Password = "socialapplication"
DBName   = "social"

[mq]
Host     = "10.0.0.137"
Port     = 5672
Username = "guest"
Password = "guest"
Vhost    = "/"

[redis]
URL    = "10.0.0.137:6379"
DB     = 0
# slave one is not used, just here for future ref
Slave= "172.16.10.17:6379"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "15s"
PostThrottleCount    = 3


[emailnotification]
templateRoot = "go/src/socialapi/workers/emailnotifier/templates/"

[sendgrid]
Username= "koding"
Password= "DEQl7_Dr"
FromName= "Koding"
FromMail= "hello@koding.com"

[sitemap]
RedisDB= 1

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "041427512bcdcd0c7bd4899ec8175f46"
ReadOnlyApiKey = "303eb858050b1067bcd704d6cbfb977c"
IndexSuffix    = ".sandbox"

[analytics]
Enabled       = false
MixpanelToken = "113c2731b47a5151f4be44ddd5af0e7a"
